// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE5IgL_3aa133lodF3jC_wO1MuNZrnaHo',
    appId: '1:805874530477:web:e24d830b5ddbf39f63ee24',
    messagingSenderId: '805874530477',
    projectId: 'sree14hari-portfolio',
    authDomain: 'sree14hari-portfolio.firebaseapp.com',
    storageBucket: 'sree14hari-portfolio.firebasestorage.app',
    measurementId: 'G-RCP47XEGZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAupMurVLnyjvXwcFoWoiS6YSG_mjhrBMY',
    appId: '1:805874530477:android:1635758c989e74f563ee24',
    messagingSenderId: '805874530477',
    projectId: 'sree14hari-portfolio',
    storageBucket: 'sree14hari-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjakY1YwyjFIVp4XG8EQNOy5I_puwHF_8',
    appId: '1:805874530477:ios:6e29d776ab9f329963ee24',
    messagingSenderId: '805874530477',
    projectId: 'sree14hari-portfolio',
    storageBucket: 'sree14hari-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.akshitMadan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjakY1YwyjFIVp4XG8EQNOy5I_puwHF_8',
    appId: '1:805874530477:ios:6e29d776ab9f329963ee24',
    messagingSenderId: '805874530477',
    projectId: 'sree14hari-portfolio',
    storageBucket: 'sree14hari-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.akshitMadan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE5IgL_3aa133lodF3jC_wO1MuNZrnaHo',
    appId: '1:805874530477:web:246690d9b2c29dd563ee24',
    messagingSenderId: '805874530477',
    projectId: 'sree14hari-portfolio',
    authDomain: 'sree14hari-portfolio.firebaseapp.com',
    storageBucket: 'sree14hari-portfolio.firebasestorage.app',
    measurementId: 'G-8WC7C6LTS7',
  );
}
